version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: laminaticus-postgres
    restart: always
    environment:
      # Default credentials; override via .env or directly here as needed
      POSTGRES_USER: laminaticus
      POSTGRES_PASSWORD: laminaticus_pass
      POSTGRES_DB: laminaticus
      # Store database files under PGDATA subdirectory to avoid pre-existing dir conflicts
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # Persist data on the host in ./db
      - ./db:/var/lib/postgresql/data
      # Run init SQL scripts on first start (table creation, migrations)
      - ./db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laminaticus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  # Empty declaration since we're using a bind mount; left here if switching to named volume
  db_data:
    external: false